version: "3"
services:

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub-tuko
    ports:
      - "4444:4444"
    environment:
      - GRID_TIMEOUT=120000
      - GRID_BROWSER_TIMEOUT=120000
      - GRID_DEBUG=true
    networks:
      - grid_network
  chrome-debug:
    image: selenium/node-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    ports:
      - "5900:5900"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION=2
    networks:
      - grid_network
  firefox-debug:
    image: selenium/node-firefox-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    ports:
      - "5901:5900"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION=2
    networks:
    - grid_network

networks:
  grid_network:

